site_name: ""
site_description: >-
  Set Cloud Up website.
theme:
  name: material
  custom_dir: docs/theme_override_home/
  # 404 page
  static_templates:
    - 404.html
  features:
    - content.code.annotate
    - content.tooltips
    - navigation.indexes
    - navigation.sections
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.top
    - navigation.tracking
    - navigation.expand
    - search.highlight
    - search.share
    - search.suggest
    - toc.follow
  font:
    text: Product Sans
    code: Roboto Mono
  language: en
  logo: assets/white-logo.png
  favicon: assets/favicon.png

  palette:
    - media: "(prefers-color-scheme: light)" 
      scheme: default
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)" 
      scheme: slate
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode

plugins:
  - search

extra_css:
  - stylesheets/extra.css

extra:
  generator: true
  social:
    - icon: fontawesome/brands/github 
      link: https://github.com/setcloudup
    - icon: fontawesome/brands/linkedin 
      link: https://www.linkedin.com/company/set-cloud-up
    - icon: fontawesome/solid/envelope
      link: mailto:oussama.bencharrada@setcloudup.com


copyright: Copyright &copy; 2023 SETCLOUDUP

markdown_extensions:
  - abbr
  - admonition
  - attr_list
  - def_list
  - footnotes
  - md_in_html
  - toc:
      permalink: true
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.details
  - pymdownx.emoji:
      emoji_generator: !!python/name:materialx.emoji.to_svg
      emoji_index: !!python/name:materialx.emoji.twemoji
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.magiclink:
      repo_url_shorthand: true
      user: squidfunk
      repo: mkdocs-material
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde

nav:
  - Home: index.md
  - About us: about-us.md 
  - Training: 
    - Training catalog: training/training-catalog.md
    - Kubernetes: 
      - Kubernetes getting started: training/kubernetes/k8s-getting-started.md
      - Kubernetes advanced: training/kubernetes/k8s-advanced.md
    # - Big Data: 
    #   - Cloud native dataplatform: training/big-data/cloud-native-dataplatform.md
  - Blog: 
    - Microservice oriented data pipeline: blog/microservice-etl.md
    - Flask REST API: 
      - blog/rest-api/index.md
      - Application: blog/rest-api/app.md
      - Terraform: blog/rest-api/terraform.md
      - Swagger: blog/rest-api/swagger.md
  - Contact: contact.md