site_name: ""
site_description: >-
  Set Cloud Up website.
theme:
  name: material
  custom_dir: docs/theme_override_home/
  # 404 page
  static_templates:
    - 404.html
  features:
    - content.code.annotate
    - content.tooltips
    - navigation.indexes
    - navigation.sections
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.top
    - navigation.tracking
    - search.highlight
    - search.share
    - search.suggest
    - toc.follow
  font:
    text: Product Sans
    code: Roboto Mono
  language: en
  logo: assets/white-logo.png
  favicon: assets/favicon.png

  palette:
    - media: "(prefers-color-scheme: light)" 
      scheme: default
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)" 
      scheme: slate
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode

plugins:
  - search

extra_css:
  - stylesheets/extra.css

extra:
  generator: true
  social:
    - icon: fontawesome/brands/github 
      link: https://github.com/setcloudup
    - icon: fontawesome/brands/linkedin 
      link: https://www.linkedin.com/company/set-cloud-up
    - icon: fontawesome/solid/envelope
      link: mailto:oussama.bencharrada@setcloudup.com


copyright: Copyright &copy; 202 SETCLOUDUP

markdown_extensions:
  - tables
  - attr_list
  - md_in_html
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg

nav:
  - Home: index.md
  - Services: services.md 
  - Training: 
    - Training catalog: training/training-catalog.md
    - Kubernetes: 
      - Kubernetes getting started: training/kubernetes/k8s-getting-started.md
      - Kubernetes advanced: training/kubernetes/k8s-advanced.md
    - Big Data: 
      - Cloud native dataplatform: training/big-data/cloud-native-dataplatform.md
  - Blog: 
    - Microservice oriented data pipeline: blog/microservice-etl.md
  - Contact: contact.md